apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: test-api
  name: test-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test-api
    spec:
      containers:
        - image: test-api
          name: test-api
          imagePullPolicy: Never
          resources: {}
          volumeMounts:
            - name: config
              mountPath: /opt/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: testapi-config
status: {}
